import { relations } from 'drizzle-orm';
import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

const syncColumns = {
  _pending_mutation: integer('_pending_mutation', { mode: 'boolean' }).notNull().default(false),
  synced_at: text('synced_at'),
};

export const users = sqliteTable('users', {
  id: text('id').primaryKey(),
  email: text('email'),
  display_name: text('display_name'),
  avatar_url: text('avatar_url'),
  target_kcal: integer('target_kcal').notNull().default(2000),
  target_protein_mg: integer('target_protein_mg'),
  target_carbs_mg: integer('target_carbs_mg'),
  target_fat_mg: integer('target_fat_mg'),
  created_at: text('created_at').notNull(),
  last_active_at: text('last_active_at').notNull(),
  ...syncColumns,
});

export const households = sqliteTable('households', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  owner_id: text('owner_id').notNull(),
  invite_code: text('invite_code'),
  created_at: text('created_at').notNull(),
  archived_at: text('archived_at'),
  ...syncColumns,
});

export const householdMembers = sqliteTable('household_members', {
  household_id: text('household_id').notNull(),
  user_id: text('user_id').notNull(),
  role: text('role').notNull(),
  joined_at: text('joined_at').notNull(),
  ...syncColumns,
});

export const globalFoodItems = sqliteTable('global_food_items', {
  id: text('id').primaryKey(),
  canonical_name: text('canonical_name').notNull(),
  brand: text('brand'),
  barcode: text('barcode'),
  category: text('category').notNull(),
  nutrition_basis: text('nutrition_basis').notNull(),
  density_mg_per_ml: integer('density_mg_per_ml'),
  kcal_per_100_unit: integer('kcal_per_100_unit').notNull(),
  protein_mg_per_100_unit: integer('protein_mg_per_100_unit').notNull(),
  carbs_mg_per_100_unit: integer('carbs_mg_per_100_unit').notNull(),
  fat_mg_per_100_unit: integer('fat_mg_per_100_unit').notNull(),
  fiber_mg_per_100_unit: integer('fiber_mg_per_100_unit'),
  default_serving_g: integer('default_serving_g'),
  default_shelf_life_days: integer('default_shelf_life_days'),
  source_type: text('source_type').notNull(),
  quality_score: real('quality_score'),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  deleted_at: text('deleted_at'),
  ...syncColumns,
});

export const personalFoodItems = sqliteTable('personal_food_items', {
  id: text('id').primaryKey(),
  user_id: text('user_id').notNull(),
  name: text('name').notNull(),
  category: text('category'),
  nutrition_basis: text('nutrition_basis').notNull(),
  density_mg_per_ml: integer('density_mg_per_ml'),
  kcal_per_100_unit: integer('kcal_per_100_unit').notNull(),
  protein_mg_per_100_unit: integer('protein_mg_per_100_unit').notNull(),
  carbs_mg_per_100_unit: integer('carbs_mg_per_100_unit').notNull(),
  fat_mg_per_100_unit: integer('fat_mg_per_100_unit').notNull(),
  linked_global_id: text('linked_global_id'),
  notes: text('notes'),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  archived_at: text('archived_at'),
  ...syncColumns,
});

export const householdFoodItems = sqliteTable('household_food_items', {
  id: text('id').primaryKey(),
  household_id: text('household_id').notNull(),
  created_by: text('created_by').notNull(),
  kind: text('kind').notNull(),
  name: text('name').notNull(),
  source_global_food_id: text('source_global_food_id'),
  source_personal_food_id: text('source_personal_food_id'),
  nutrition_basis: text('nutrition_basis').notNull(),
  density_mg_per_ml: integer('density_mg_per_ml'),
  kcal_per_100_unit: integer('kcal_per_100_unit').notNull(),
  protein_mg_per_100_unit: integer('protein_mg_per_100_unit').notNull(),
  carbs_mg_per_100_unit: integer('carbs_mg_per_100_unit').notNull(),
  fat_mg_per_100_unit: integer('fat_mg_per_100_unit').notNull(),
  default_unit_display: text('default_unit_display'),
  sharing_mode: text('sharing_mode').notNull(),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  archived_at: text('archived_at'),
  ...syncColumns,
});

export const foodVariations = sqliteTable('food_variations', {
  id: text('id').primaryKey(),
  canonical_food_id: text('canonical_food_id'),
  created_by: text('created_by').notNull(),
  household_id: text('household_id'),
  scope: text('scope').notNull(),
  status: text('status').notNull(),
  name: text('name').notNull(),
  brand: text('brand'),
  barcode: text('barcode'),
  category: text('category'),
  nutrition_basis: text('nutrition_basis').notNull(),
  density_mg_per_ml: integer('density_mg_per_ml'),
  kcal_per_100_unit: integer('kcal_per_100_unit'),
  protein_mg_per_100_unit: integer('protein_mg_per_100_unit'),
  carbs_mg_per_100_unit: integer('carbs_mg_per_100_unit'),
  fat_mg_per_100_unit: integer('fat_mg_per_100_unit'),
  image_url: text('image_url'),
  notes: text('notes'),
  evidence_count: integer('evidence_count').notNull().default(0),
  source_context: text('source_context'),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  archived_at: text('archived_at'),
  ...syncColumns,
});

export const privateInventoryItems = sqliteTable('private_inventory_items', {
  id: text('id').primaryKey(),
  user_id: text('user_id').notNull(),
  household_id: text('household_id').notNull(),
  global_food_id: text('global_food_id'),
  personal_food_id: text('personal_food_id'),
  household_food_item_id: text('household_food_item_id'),
  dish_batch_id: text('dish_batch_id'),
  food_variation_id: text('food_variation_id'),
  snapshot_food_name: text('snapshot_food_name').notNull(),
  snapshot_nutrition_basis: text('snapshot_nutrition_basis').notNull(),
  snapshot_kcal_per_100_unit: integer('snapshot_kcal_per_100_unit').notNull(),
  snapshot_protein_mg_per_100_unit: integer('snapshot_protein_mg_per_100_unit').notNull(),
  snapshot_carbs_mg_per_100_unit: integer('snapshot_carbs_mg_per_100_unit').notNull(),
  snapshot_fat_mg_per_100_unit: integer('snapshot_fat_mg_per_100_unit').notNull(),
  snapshot_category: text('snapshot_category'),
  snapshot_density_mg_per_ml: integer('snapshot_density_mg_per_ml'),
  quantity_base: integer('quantity_base').notNull(),
  base_unit: text('base_unit').notNull(),
  unit_display: text('unit_display').notNull(),
  storage_label: text('storage_label'),
  estimated_expiry: text('estimated_expiry'),
  version: integer('version').notNull().default(1),
  added_by: text('added_by').notNull(),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  archived_at: text('archived_at'),
  ...syncColumns,
});

export const fridgeItems = sqliteTable('fridge_items', {
  id: text('id').primaryKey(),
  household_id: text('household_id').notNull(),
  global_food_id: text('global_food_id'),
  personal_food_id: text('personal_food_id'),
  household_food_item_id: text('household_food_item_id'),
  dish_batch_id: text('dish_batch_id'),
  food_variation_id: text('food_variation_id'),
  snapshot_food_name: text('snapshot_food_name').notNull(),
  snapshot_nutrition_basis: text('snapshot_nutrition_basis').notNull(),
  snapshot_kcal_per_100_unit: integer('snapshot_kcal_per_100_unit').notNull(),
  snapshot_protein_mg_per_100_unit: integer('snapshot_protein_mg_per_100_unit').notNull(),
  snapshot_carbs_mg_per_100_unit: integer('snapshot_carbs_mg_per_100_unit').notNull(),
  snapshot_fat_mg_per_100_unit: integer('snapshot_fat_mg_per_100_unit').notNull(),
  snapshot_category: text('snapshot_category'),
  snapshot_density_mg_per_ml: integer('snapshot_density_mg_per_ml'),
  quantity_base: integer('quantity_base').notNull(),
  base_unit: text('base_unit').notNull(),
  unit_display: text('unit_display').notNull(),
  estimated_expiry: text('estimated_expiry'),
  version: integer('version').notNull().default(1),
  added_by: text('added_by').notNull(),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  archived_at: text('archived_at'),
  ...syncColumns,
});

export const diaryEntries = sqliteTable('diary_entries', {
  id: text('id').primaryKey(),
  user_id: text('user_id').notNull(),
  household_id: text('household_id').notNull(),
  food_name: text('food_name').notNull(),
  source_scope: text('source_scope').notNull(),
  source_global_food_id: text('source_global_food_id'),
  source_personal_food_id: text('source_personal_food_id'),
  source_household_food_item_id: text('source_household_food_item_id'),
  source_private_inventory_item_id: text('source_private_inventory_item_id'),
  source_fridge_item_id: text('source_fridge_item_id'),
  source_dish_batch_id: text('source_dish_batch_id'),
  quantity_base: integer('quantity_base').notNull(),
  base_unit: text('base_unit').notNull(),
  kcal: integer('kcal').notNull(),
  protein_mg: integer('protein_mg').notNull(),
  carbs_mg: integer('carbs_mg').notNull(),
  fat_mg: integer('fat_mg').notNull(),
  source: text('source'),
  confidence: real('confidence'),
  is_quick_estimate: integer('is_quick_estimate', { mode: 'boolean' }).notNull().default(false),
  is_correction: integer('is_correction', { mode: 'boolean' }).notNull().default(false),
  corrects_entry_id: text('corrects_entry_id'),
  serve_split_event_id: text('serve_split_event_id'),
  logged_at: text('logged_at').notNull(),
  created_at: text('created_at').notNull(),
  ...syncColumns,
});

export const dailySummaries = sqliteTable('daily_summaries', {
  id: text('id').primaryKey(),
  user_id: text('user_id').notNull(),
  date: text('date').notNull(),
  total_kcal: integer('total_kcal').notNull().default(0),
  total_protein_mg: integer('total_protein_mg').notNull().default(0),
  total_carbs_mg: integer('total_carbs_mg').notNull().default(0),
  total_fat_mg: integer('total_fat_mg').notNull().default(0),
  entry_count: integer('entry_count').notNull().default(0),
  ...syncColumns,
});

export const aiCaptureSessions = sqliteTable('ai_capture_sessions', {
  id: text('id').primaryKey(),
  user_id: text('user_id').notNull(),
  household_id: text('household_id').notNull(),
  capture_type: text('capture_type').notNull(),
  source_image_url: text('source_image_url'),
  raw_text: text('raw_text'),
  status: text('status').notNull(),
  error_message: text('error_message'),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  committed_at: text('committed_at'),
  ...syncColumns,
});

export const aiCaptureItems = sqliteTable('ai_capture_items', {
  id: text('id').primaryKey(),
  session_id: text('session_id').notNull(),
  raw_text: text('raw_text'),
  resolved_scope: text('resolved_scope'),
  resolved_food_id: text('resolved_food_id'),
  resolved_variation_id: text('resolved_variation_id'),
  quantity_raw: text('quantity_raw'),
  quantity_base: integer('quantity_base'),
  base_unit: text('base_unit'),
  confidence: real('confidence').notNull(),
  suggested_destination: text('suggested_destination'),
  action: text('action'),
  committed_diary_entry_id: text('committed_diary_entry_id'),
  committed_inventory_item_id: text('committed_inventory_item_id'),
  commit_error: text('commit_error'),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  ...syncColumns,
});

export const dishBatches = sqliteTable('dish_batches', {
  id: text('id').primaryKey(),
  household_id: text('household_id').notNull(),
  created_by: text('created_by').notNull(),
  recipe_template_id: text('recipe_template_id'),
  household_food_item_id: text('household_food_item_id'),
  name: text('name').notNull(),
  output_inventory_scope: text('output_inventory_scope').notNull(),
  output_inventory_item_id: text('output_inventory_item_id'),
  output_quantity_base: integer('output_quantity_base').notNull(),
  base_unit: text('base_unit').notNull(),
  nutrition_basis: text('nutrition_basis').notNull(),
  kcal_total: integer('kcal_total').notNull(),
  protein_mg_total: integer('protein_mg_total').notNull(),
  carbs_mg_total: integer('carbs_mg_total').notNull(),
  fat_mg_total: integer('fat_mg_total').notNull(),
  status: text('status').notNull(),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  ...syncColumns,
});

export const dishBatchIngredients = sqliteTable('dish_batch_ingredients', {
  id: text('id').primaryKey(),
  dish_batch_id: text('dish_batch_id').notNull(),
  source_private_inventory_item_id: text('source_private_inventory_item_id'),
  source_fridge_item_id: text('source_fridge_item_id'),
  source_snapshot_food_name: text('source_snapshot_food_name').notNull(),
  quantity_used_base: integer('quantity_used_base').notNull(),
  base_unit: text('base_unit').notNull(),
  kcal_contributed: integer('kcal_contributed').notNull(),
  protein_mg_contributed: integer('protein_mg_contributed').notNull(),
  carbs_mg_contributed: integer('carbs_mg_contributed').notNull(),
  fat_mg_contributed: integer('fat_mg_contributed').notNull(),
  created_at: text('created_at').notNull(),
  ...syncColumns,
});

export const serveSplitEvents = sqliteTable('serve_split_events', {
  id: text('id').primaryKey(),
  household_id: text('household_id').notNull(),
  created_by: text('created_by').notNull(),
  dish_batch_id: text('dish_batch_id').notNull(),
  total_quantity_base: integer('total_quantity_base').notNull(),
  base_unit: text('base_unit').notNull(),
  total_kcal: integer('total_kcal').notNull(),
  total_protein_mg: integer('total_protein_mg').notNull(),
  total_carbs_mg: integer('total_carbs_mg').notNull(),
  total_fat_mg: integer('total_fat_mg').notNull(),
  status: text('status').notNull(),
  created_at: text('created_at').notNull(),
  expires_at: text('expires_at').notNull(),
  ...syncColumns,
});

export const serveSplitPortions = sqliteTable('serve_split_portions', {
  id: text('id').primaryKey(),
  event_id: text('event_id').notNull(),
  user_id: text('user_id').notNull(),
  percentage: real('percentage'),
  quantity_base: integer('quantity_base').notNull(),
  base_unit: text('base_unit').notNull(),
  kcal: integer('kcal').notNull(),
  protein_mg: integer('protein_mg').notNull(),
  carbs_mg: integer('carbs_mg').notNull(),
  fat_mg: integer('fat_mg').notNull(),
  status: text('status').notNull(),
  diary_entry_id: text('diary_entry_id'),
  responded_at: text('responded_at'),
  ...syncColumns,
});

export const recipeTemplates = sqliteTable('recipe_templates', {
  id: text('id').primaryKey(),
  owner_scope: text('owner_scope').notNull(),
  owner_user_id: text('owner_user_id'),
  owner_household_id: text('owner_household_id'),
  household_food_item_id: text('household_food_item_id'),
  name: text('name').notNull(),
  default_output_quantity_base: integer('default_output_quantity_base'),
  default_output_base_unit: text('default_output_base_unit'),
  notes: text('notes'),
  created_from_dish_batch_id: text('created_from_dish_batch_id'),
  created_at: text('created_at').notNull(),
  updated_at: text('updated_at').notNull(),
  archived_at: text('archived_at'),
  ...syncColumns,
});

export const recipeTemplateIngredients = sqliteTable('recipe_template_ingredients', {
  id: text('id').primaryKey(),
  recipe_template_id: text('recipe_template_id').notNull(),
  preferred_scope: text('preferred_scope').notNull(),
  global_food_id: text('global_food_id'),
  personal_food_id: text('personal_food_id'),
  household_food_item_id: text('household_food_item_id'),
  quantity_base: integer('quantity_base').notNull(),
  base_unit: text('base_unit').notNull(),
  created_at: text('created_at').notNull(),
  ...syncColumns,
});

export const householdsRelations = relations(households, ({ many }) => ({
  members: many(householdMembers),
}));

export const householdMembersRelations = relations(householdMembers, ({ one }) => ({
  household: one(households, {
    fields: [householdMembers.household_id],
    references: [households.id],
  }),
  user: one(users, {
    fields: [householdMembers.user_id],
    references: [users.id],
  }),
}));

export const usersRelations = relations(users, ({ many }) => ({
  memberships: many(householdMembers),
}));
