export const palette = {
  background: '#FFF3F9',
  surface: '#FFF3F9',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#FFEBF7',
  surfaceContainer: '#FFDFF6',
  surfaceContainerHigh: '#FFD7F5',
  surfaceContainerHighest: '#FFCEF4',
  onSurface: '#442340',
  onSurfaceVariant: '#754F6F',
  outline: '#936A8C',
  outlineVariant: '#CD9FC4',
  primary: '#9E316D',
  primaryDim: '#8F2461',
  primaryContainer: '#F97BBA',
  onPrimary: '#FFEFF3',
  onPrimaryContainer: '#530034',
  secondary: '#04647D',
  secondaryContainer: '#9AE1FF',
  onSecondaryContainer: '#005267',
  tertiary: '#635D00',
  tertiaryContainer: '#FAF04B',
  error: '#B41340',
  errorContainer: '#F74B6D',
  onErrorContainer: '#510017',
  electricPink: '#FF2D78',
  electricCyan: '#00FFCC',
  electricYellow: '#FFE04A',
  nightBackground: '#0A0A12',
  white: '#FFFFFF',
  black: '#0A0710',
} as const;

export type ColorScheme = 'light' | 'dark';

export const colors = {
  light: {
    background: palette.background,
    surface: palette.surface,
    surfaceElevated: palette.surfaceContainerLowest,
    surfaceMuted: palette.surfaceContainerLow,
    surfaceContainer: palette.surfaceContainer,
    surfaceContainerHigh: palette.surfaceContainerHigh,
    surfaceContainerHighest: palette.surfaceContainerHighest,
    border: palette.outlineVariant,
    borderStrong: palette.outline,
    text: palette.onSurface,
    textMuted: palette.onSurfaceVariant,
    textInverse: palette.onPrimary,
    primary: palette.primary,
    primaryDim: palette.primaryDim,
    primaryForeground: palette.onPrimary,
    primarySoft: palette.surfaceContainerHigh,
    primaryContainer: palette.primaryContainer,
    onPrimaryContainer: palette.onPrimaryContainer,
    secondary: palette.secondary,
    secondaryContainer: palette.secondaryContainer,
    tertiary: palette.tertiary,
    tertiaryContainer: palette.tertiaryContainer,
    destructive: palette.error,
    destructiveForeground: palette.onPrimary,
    destructiveSoft: '#FFE3EC',
    success: palette.secondary,
    successSoft: palette.secondaryContainer,
    warning: palette.tertiary,
    warningSoft: palette.tertiaryContainer,
    info: palette.secondary,
    infoSoft: palette.secondaryContainer,
    electricPink: palette.electricPink,
    electricCyan: palette.electricCyan,
    electricYellow: palette.electricYellow,
    inputBackground: palette.surfaceContainerLowest,
    inputPlaceholder: palette.outline,
    disabledSurface: palette.surfaceContainerLow,
    disabledText: palette.outline,
    overlay: 'rgba(15, 23, 42, 0.16)',
    backdrop: 'rgba(68, 35, 64, 0.46)',
    shadow: palette.black,
  },
  dark: {
    background: palette.nightBackground,
    surface: '#17101C',
    surfaceElevated: '#241428',
    surfaceMuted: '#301A35',
    surfaceContainer: '#3A1F3F',
    surfaceContainerHigh: '#48244E',
    surfaceContainerHighest: '#552859',
    border: '#6F4370',
    borderStrong: '#B681B2',
    text: '#FFF3F9',
    textMuted: '#E4B8D8',
    textInverse: palette.nightBackground,
    primary: palette.primaryContainer,
    primaryDim: palette.primary,
    primaryForeground: palette.onPrimaryContainer,
    primarySoft: 'rgba(249, 123, 186, 0.22)',
    primaryContainer: palette.primaryContainer,
    onPrimaryContainer: palette.onPrimaryContainer,
    secondary: palette.secondaryContainer,
    secondaryContainer: palette.secondary,
    tertiary: palette.electricYellow,
    tertiaryContainer: 'rgba(255, 224, 74, 0.16)',
    destructive: '#FF87A0',
    destructiveForeground: palette.onErrorContainer,
    destructiveSoft: 'rgba(247, 75, 109, 0.22)',
    success: palette.electricCyan,
    successSoft: 'rgba(0, 255, 204, 0.14)',
    warning: palette.electricYellow,
    warningSoft: 'rgba(255, 224, 74, 0.16)',
    info: palette.secondaryContainer,
    infoSoft: 'rgba(154, 225, 255, 0.16)',
    electricPink: palette.electricPink,
    electricCyan: palette.electricCyan,
    electricYellow: palette.electricYellow,
    inputBackground: '#2C1831',
    inputPlaceholder: '#B681B2',
    disabledSurface: '#251429',
    disabledText: '#8B6386',
    overlay: 'rgba(255, 206, 244, 0.12)',
    backdrop: 'rgba(10, 10, 18, 0.74)',
    shadow: palette.black,
  },
} as const;

export type ThemeColors = (typeof colors)[ColorScheme];
